Changed Project's Struct Member Alignment from /Zp1 to Inherit from Parent or Project Defaults
Resolves error C2338: Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined

Setting change located in Config Property > C/C++ > Code Generation